exclude: '\.idea/|\.vscode/'
minimum_pre_commit_version: 4.4.0
default_language_version:
  python: '3.13'
  node: '24.11.1'
repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types: [tsv]
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0
    hooks:
      - id: markdownlint
        args: [
            "--disable",
            "MD013", # Line length
            "MD033", # Inline HTML
            "--", # otherwise files are interpreted as args
          ]
  # shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"]
  - repo: https://github.com/randolf-scholz/latex-hooks.git
    rev: v0.0.16
    hooks:
      - id: check-separator-length-88
      - id: latex-avoid-legacy-packages
      - id: latex-avoid-legacy-options
      - id: latex-avoid-legacy-commands
      - id: latex-avoid-legacy-environments
      - id: latex-avoid-def
      - id: latex-avoid-let
      - id: latex-avoid-newcommand
      - id: latex-avoid-legacy-hooks
      - id: latex-avoid-double-dollar
      - id: chktex
      - id: lacheck
